[NOTRACKER] Upgrade middleman version
EENCloud/api-docs pull request #94
Opened 2020-09-14 13:36 UTC by michalboruch

There is a mismatch between the `middleman` version in Gemfile and Gemfile.lock
```
Step 5/11 : RUN bundle install && bundle exec middleman build --clean --verbose
 ---> Running in ae4e2b1e5a5f
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "middleman-core":
  In snapshot (Gemfile.lock):
    middleman-core (= 4.3.5)

  In Gemfile:
    middleman (~> 4.2.0) was resolved to 4.2.0, which depends on
      middleman-core (= 4.2.0)

    middleman-autoprefixer (~> 2.10.1) was resolved to 2.10.1, which depends on
      middleman-core (>= 3.3.3)

    middleman-livereload (~> 3.4.6) was resolved to 3.4.6, which depends on
      middleman-core (>= 3.3)

    middleman-sprockets (~> 4.1.0) was resolved to 4.1.1, which depends on
      middleman-core (~> 4.0)

    middleman-syntax (~> 3.0.0) was resolved to 3.0.0, which depends on
      middleman-core (>= 3.2)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
ERROR: Service 'apidoc' failed to build: The command '/bin/sh -c bundle install && bundle exec middleman build --clean --verbose' returned a non-zero code: 6
```

2020-09-14 15:11 UTC, mrauer requested changes
It was not able to build because of a conflict with `mini_racer`.

But if you bump the mini_racer version from `0.2.6` to `0.3.1` (the most recent) then it works.

After this, approved :+1:

2020-09-14 16:13 UTC, michalboruch commented
@mrauer You're right, it was my local `.lock` I assumed that we're keeping it in the repo. Thanks

2020-09-16 13:57 UTC, mrauer approved these changes

2020-09-17 06:50 UTC, janeek1995 commented
:+1:

2020-09-17 07:00 UTC, merged